SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_SPAWN_RATE_SECONDS = ASTEROID_SPAWN_RATE
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_ACCELERATION = 400
PLAYER_MAX_SPEED = 350
PLAYER_FRICTION = 0.985
PLAYER_START_LIVES = 3
PLAYER_RESPAWN_INVULNERABILITY = 3.0  # seconds

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
RAPID_SHOOT_COOLDOWN = 0.12

SCORE_LARGE = 20
SCORE_MEDIUM = 50
SCORE_SMALL = 100

POWERUP_RADIUS = 14
POWERUP_DROP_CHANCE = 0.28  # 28% drop rate on split/kill
POWERUP_DURATION = 10.0      # seconds for speed/triple shot
BOMB_STARTING_COUNT = 2
BOMB_BLAST_RADIUS = 280
BOMB_FUSE_SECONDS = 1.2